# ---
# title: Helper functions for handling ensemble data
# author: Bryan Alpecho
# date: 2026 Feb 12 - 
# output: csv and plot for predictions
# ---

#These are additional functions to help in visualizing and summarizing the ensemble for predicting the zooplankton trophic groups (6b_predict_globalCPR)
#01 to plot ensemble at 2015 and 2100
#02 to plot for delta of chlos between 2015 and 2100
#03 to compute for summary statistics of chlos projections

#Load libraries
packages <- c("tidyverse",
              "stars",
              "tmap",
              "marginaleffects")

# Function to download the packages if necessary. Otherwise, these are loaded.
package.check <- lapply(
  packages,
  FUN = function(x)
  {
    if (!require(x, character.only = TRUE))
    {
      install.packages(x, dependencies = TRUE,
                       repos = "http://cran.us.r-project.org")
      library(x, character.only = TRUE)
    }
  }
)
  
#setup directory
  # # set date
  # date <- "25022026"
  # # define variable
  # var <- "chlos"
  # # access ESM output
  # base_dir <- "./hotrstuff/" # Just start relative to this location

# Create a publication-ready theme (Adapted from 2025 UQ MME Lab Winter R Workshop)
pub_theme <- theme_classic(base_size = 10, base_family = "sans") + # Family including Arial, Helvetica, Futura, Verdana, and Calibri
  theme(
    # Axis styling
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12, colour = "black"),
    axis.line = element_line(colour = "black", linewidth = 0.5),
    axis.ticks = element_line(colour = "black", linewidth = 0.5),
    
    # Legend styling
    legend.title = element_text(size = 10, face = "bold"),
    legend.text = element_text(size = 8),
    legend.position = "inside",
    #legend.position.inside = c(0.85, 0.25),
    legend.background = element_rect(fill = "white", colour = "black", linewidth = 0.5),
    legend.margin = margin(2, 2, 2, 2),
    
    # Panel styling
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    
    # Remove grid lines for cleaner look
    panel.grid = element_blank()
  )

##01 to plot annual mean of chlos median ensemble from 2015 to 2100

  plot_delta_chlos <- function(ensemble){
    ssp_list <- c()
    #to create df for merged chlos projections under each ssp scenario
    m_projection <- tibble(experiment = character(length = 0),
                           year = numeric(length = 0),
                           annual_median = numeric(length = 0),
                           annual_sd = numeric(length = 0),
                           annual_median_u = numeric(length = 0),
                           annual_median_l = numeric(length = 0))
    
    dir_historical_ensemble <- "data_input/ensemble_chlos/median/chlos/chlos_Omon_ensemble_historical_r1i1p1f1_RegriddedAnnual_18500101-20141231.nc"
    
    hist_ens <- read_stars(dir_historical_ensemble, quiet = TRUE, proxy = TRUE) %>% setNames("chlos")
    print(paste0("Loaded projections under historical scenario"))
    
    #to convert chlos (kg/m^3) to chla_sqrt (sqrt (mg/m^3) )
    chla_sqrt <- function(x){ sqrt(x * 1000000) } 
    
    hist_converted <- st_apply(hist_ens,1:3, chla_sqrt, rename = TRUE)  
    
    ### Following code generated by AI
    #through a Gemini prompt of "R how to generate a new dimension of stars object indicating year from a time dimension that is a CFTime_365_day (e.g. 2015-07-01T06:00:00).'
    #to extract time values from the original object
    hist_time_meta <- st_dimensions(hist_ens)$time$values
    
    #to convert the CFtime object into readable strings
    hist_time_strings <- hist_time_meta$as_timestamp()
    
    #to extract the 4-digit years from the string (199_, 200_, ...)
    hist_years <- as.numeric(substr(hist_time_strings, 1, 4))
    
    #to overwrite the time dimension
    hist_converted <- st_set_dimensions(hist_converted, "time", values = hist_years, names = "year")
    ###
    
    #to convert star to df
    df_hist <- as.data.frame(hist_converted, xy = TRUE, na.rm = FALSE) #xy coordinates and kept 'NA'
    #to simplify esm_df   
    df_hist <- df_hist %>% select(c("chla_sqrt","x","y","year"))
    
    #to subset baseline (1980-2000) and recent past (1980-2014)
    baseline <- df_hist %>% 
      filter(year >= 1980 & year <= 2000) %>%
      group_by(x,y) %>% 
      summarize("hist_chla_sqrt" = mean(chla_sqrt, na.rm = T)) #mean or median
    
    #to compute for delta in recent past relative to baseline (1980-2000)
    recentPast <- df_hist %>% 
      filter(year >= 1980 & year <= 2014) 
    
    recentPast_calc <- recentPast %>% 
      left_join(baseline, by = join_by("x","y")) %>% 
      mutate(delta = ((chla_sqrt - hist_chla_sqrt)/hist_chla_sqrt) * 100)
    
    recentPast_summary <- recentPast_calc %>%   
      group_by(year) %>% 
      summarise(annual_median = median(delta, na.rm = T), 
                annual_sd = sd(delta, na.rm = T)) 
    
    recentPast_summary <- recentPast_summary %>% 
      mutate(annual_median_u = annual_median + annual_sd,
             annual_median_l = annual_median - annual_sd)
    
    for(i in 1:length(ensemble)){
        
        cur_ens <- ensemble[i]
        #1.1 identify ssp scenario
        ssp_scenario <- str_extract(basename(cur_ens), "ssp\\d{3}|historical")
        
            if(ssp_scenario == "historical"){
              print("Skipping historical ensemble from input (ensemble list)")
              next
            }else{print(paste0("Projections under ",ssp_scenario," scenario"))}
        
        ssp_list <- c(ssp_list, ssp_scenario)
        #to include recentPast to 'm_projection' df 
        recentPast_summary <- recentPast_summary %>% 
          mutate(experiment = ssp_scenario) #in order to merge recentPast data with the projection scenarios
        m_projection <- m_projection %>% 
          rows_insert(recentPast_summary, by = "experiment")
        
        #to process projections under ssp scenarios
        #1.1 load ensemble
        ens_selected <- read_stars(cur_ens, quiet = TRUE, proxy = TRUE) %>% setNames("chlos")
        
          esm_converted <- st_apply(ens_selected,1:3, chla_sqrt, rename = TRUE)  
        
          ### Following code generated by AI
          #through a Gemini prompt of "R how to generate a new dimension of stars object indicating year from a time dimension that is a CFTime_365_day (e.g. 2015-07-01T06:00:00).'
          #to extract time values from the original object
          time_meta <- st_dimensions(ens_selected)$time$values
          
          #to convert the CFtime object into readable strings
          time_strings <- time_meta$as_timestamp()
          
          #to extract the 4-digit years from the string (199_, 200_, ...)
          years <- as.numeric(substr(time_strings, 1, 4))
        
          #to overwrite the time dimension
          esm_converted <- st_set_dimensions(esm_converted, "time", values = years, names = "year")
          ###
        
          #to convert star to df
          projection <- as.data.frame(esm_converted, xy = TRUE, na.rm = FALSE) #xy coordinates and kept 'NA'
          #to simplify esm_df   
          projection <- projection %>% select(c("chla_sqrt","x","y","year"))
              
          projection_calc <- projection %>% 
            left_join(baseline, by = join_by("x","y")) %>% 
            mutate(delta = ((chla_sqrt - hist_chla_sqrt)/hist_chla_sqrt) * 100)
          
          projection_summary <- projection_calc %>%   
            group_by(year) %>% 
            summarise(annual_median = median(delta, na.rm = T), 
                      annual_sd = sd(delta, na.rm = T)) %>% 
            mutate(experiment = ssp_scenario)
          
          projection_summary <- projection_summary %>% 
            mutate(annual_median_u = annual_median + annual_sd,
                   annual_median_l = annual_median - annual_sd)
          
          #to save each iteration of projection summary to 'm_projection' df 
          m_projection <- m_projection %>% 
            rows_append(projection_summary)
        
    }
    
    ylims = round(c(min(m_projection$annual_median_l),max(m_projection$annual_median_u)),0)
    
    #to plot
    plot <- ggplot(data = m_projection) + pub_theme +
      geom_ribbon(aes(x = year, y = annual_median,
                      ymin = annual_median_l, ymax = annual_median_u, colour = factor(experiment), fill = factor(experiment)), alpha = 0.1, linetype=2, show.legend = F) +
      geom_line(aes(x = year, y = annual_median, colour=factor(experiment))) +
      geom_hline(yintercept = 0, color = "black", linetype = "dashed" )+
      labs(y = bquote(Delta~sqrt("Chl-a")~"(%)"), x = "Year") +
      coord_cartesian(ylim = ylims, xlim = c(1980,2100)) +
      scale_x_continuous(breaks = seq(1980, 2100, by = 20)) +
      theme(legend.title = element_blank(), legend.position = "right", axis.title = element_text(size = 12)) +
      scale_colour_discrete(labels=toupper(ssp_list)) 
    
    ggsave(paste0("output/plots/projections_chlos_",date,".png"), plot = plot,
           width = 8, height = 10, dpi = 300)
    print(paste0("output/plots/projections_chlos_",date,".png"))
    
    
    #to print out summary of delta 
    #to subset future (2080-2100)
    m_projection_sel <- m_projection %>% filter(year >= 2080 & year <= 2100) 
    
    #to summarize delta by future (2080-2100) relative to baseline (1980-2000) and print out
    delta_perc_summary <- m_projection_sel %>% group_by(experiment) %>% 
      summarise(mean_delta_perc = mean(annual_median_l, na.rm =T), 
                median_delta_perc = median(annual_median, na.rm =T), 
                Q1_delta_perc = quantile(annual_median, 0.25, na.rm =T), 
                Q3_delta_perc = quantile(annual_median, 0.75, na.rm =T), 
                min_delta_perc = min(annual_median, na.rm = T),
                max_delta_perc = max(annual_median, na.rm = T))
    
    assign("chlos_summary", delta_perc_summary, envir = .GlobalEnv)
    print("Saved in Global Env: chlos_summary")
  }
    
##02 to plot ensemble at 2015 and 2100
  # #select ensemble
  # ensemble_median <- list.files(file.path(base_dir, "data", "proc", "ensemble", "median", var), full.names = TRUE)
  # 
  # ens_selected <- read_stars(ensemble_median, quiet = TRUE, proxy = TRUE) %>% setNames("chlos")
  # ens_name <- str_extract(basename(ensemble_median), ".*(?=\\.nc)")
  # #ens_snapshot_baseline <- ens_selected[,,,1] #2015:1 :: 2100:86
  # #ens_snapshot_future <- ens_selected[,,,86] 
  
  #to plot ensemble snapshot function
  plot_esm_snapshot <- function(ens){
    ensemble <- read_stars(ens)
      ens_name <- str_extract(basename(ens), ".*(?=\\_r1i1p1f1_RegriddedAnnual_20150101-21001231.nc)")
    
    #convert chlos (kg/m^3) to chla_sqrt (sqrt (mg/m^3) )
    chla_sqrt <- function(x){ sqrt(x * 1000000) }
    ens_converted <- st_apply(ensemble,1:3, chla_sqrt, rename = TRUE)
    
    ens_snapshot_baseline <- ens_converted[,,,1] #2015:1 :: 2100:86
    ens_snapshot_future <- ens_converted[,,,86]
    
    ens_list <- list(ens_snapshot_baseline, ens_snapshot_future)
    names(ens_list) <- c("baseline_2015","future_2100")
    for(i in 1:length(ens_list)){
      #ens_st <- st_as_stars(ens_list[i], dims = c("x","y"))
      #to plot
      TG_projection <- tm_shape(ens_list[[i]]) +
        tm_raster(
          col = "chla_sqrt",      # The name of your data column
          col.scale = tm_scale_continuous(values = c("white", "darkgreen")),
          col.legend = tm_legend(paste0("Chl os ensemble ",names(ens_list[i])),
                                 orientation = "landscape", 
                                 frame = FALSE,
                                 position = tm_pos_out("center", "bottom"))) +
        tm_layout(legend.outside = TRUE, bg.color = "black") 
      #to save plot
      tmap_save(TG_projection, filename=paste0("output/plots/",ens_name,"_",names(ens_list[i]),"_",date,".png"))
    }
  }

  #plot_esm_snapshot(ens_snapshot_baseline)
  
##03 to plot ensemble delta function 
  plot_esm_delta <- function(ens){
    #read in ensemble as stars object
    ens_selected <- read_stars(ens, quiet = TRUE, proxy = TRUE) %>% setNames("chlos")
    ens_name <- str_extract(basename(ens), ".*(?=\\_r1i1p1f1_RegriddedAnnual_20150101-21001231.nc)")
    print(paste0("SSP scenario in process: ",ens_name))
    
    str_extract(basename(ens), "_ssp\\d{3}_")
    
    #convert chlos (kg/m^3) to chla_sqrt (sqrt (mg/m^3) )
    chla_sqrt <- function(x){ sqrt(x * 1000000) }
    esm_converted <- st_apply(ens_selected,1:3, chla_sqrt, rename = TRUE)
    #separate baseline (2015) and future (2100) snapshot of chlos projections
    ens_snapshot_baseline <- esm_converted[,,,1] #2015:1 :: 2100:86
    ens_snapshot_future <- esm_converted[,,,86]
    
    #convert star to df
    ens_baseline_df <- as.data.frame(ens_snapshot_baseline, xy = TRUE, na.rm = T) %>% rename("chla_sqrt_baseline" = "chla_sqrt")
    #xy coordinates and kept 'NA'
    ens_future_df <- as.data.frame(ens_snapshot_future, xy = TRUE, na.rm = T) %>% rename("chla_sqrt_future" = "chla_sqrt")
    #xy coordinates and kept 'NA'

    #compute for delta
    ens_delta_summary <- ens_baseline_df %>% select("chla_sqrt_baseline", "x", "y") %>% 
      left_join(ens_future_df %>% select("chla_sqrt_future", "x", "y"), by = c("x","y")) %>% 
      mutate("chla_delta" = (((chla_sqrt_future - chla_sqrt_baseline)/chla_sqrt_baseline)*100))
      
    #save
    saveRDS(ens_delta_summary, file=paste0("output/projections/Delta_",ens_name,"_",date,".RData"))
    print(paste0("File (computed delta) saved: output/projections/Delta_",ens_name,"_",date,".RData"))

    #to plot
    #convert to stars
    st_projections <- st_as_stars(ens_delta_summary, dims = c("x","y"))
    
    #print(summary(is.na(st_projections$chla_sqrt_delta)))
    TG_projection <- tm_shape(st_projections) +
      tm_raster(
        col = "chla_delta",      # The name of your data column
        col.scale = tm_scale_continuous(midpoint = 0, values = c("blue", "white","red")),
        col.legend = tm_legend(paste("Change in surface chlorophyll under climate change (SSP585)",sep=""),
                               orientation = "landscape", 
                               frame = FALSE)) +
      tm_layout(legend.outside = TRUE, bg.color = "black", text.size = 36) 
    
    tmap_save(TG_projection, filename=paste0("output/plots/chlos_delta_",date,".png"))
    print(paste0("Plot saved: output/plots/chlos_delta_",date,".png"))
  }
  
  #plot_esm_delta(ens_selected)
  
##04 to compute for summary statistics of chlos
  
  summary_stats_chlos <- function(ensemble_list){
    for(i in 1:length(ensemble_list)){
      
      ens_selected <- read_stars(ensemble_list[i], quiet = TRUE, proxy = TRUE) %>% setNames("chlos")
      ens_name <- str_extract(basename(ensemble_list[i]), ".*(?=\\.nc)")
      
      #convert chlos (kg/m^3) to chla_sqrt (sqrt (mg/m^3) )
      chla_sqrt <- function(x){ sqrt(x * 1000000) }
      esm_converted <- st_apply(ens_selected,1:3, chla_sqrt, rename = TRUE)
      
      ens_snapshot_baseline <- esm_converted[,,,1] #2015:1 :: 2100:86
      ens_snapshot_future <- esm_converted[,,,86]
      
      #convert star to df
      ens_baseline_df <- as.data.frame(ens_snapshot_baseline, xy = TRUE, na.rm = T) %>% rename("chla_sqrt_baseline" = "chla_sqrt")
      #xy coordinates and kept 'NA'
      ens_future_df <- as.data.frame(ens_snapshot_future, xy = TRUE, na.rm = T) %>% rename("chla_sqrt_future" = "chla_sqrt")
      #xy coordinates and kept 'NA'
      
      options(digits = 10)
      ens_baseline_summary <- ens_baseline_df %>% 
        summarise(mean = mean(chla_sqrt_baseline, na.rm =T), 
                  median = median(chla_sqrt_baseline, na.rm =T), 
                  Q1 = quantile(chla_sqrt_baseline, 0.25, na.rm =T), 
                  Q3 = quantile(chla_sqrt_baseline, 0.75, na.rm =T), 
                  min = min(chla_sqrt_baseline, na.rm = T),
                  max = max(chla_sqrt_baseline, na.rm = T))
      
      print(paste("Ensemble: ",ens_name,sep=""))
      print("Baseline (yr 2015)")
      print(ens_baseline_summary) 
      
      ens_future_summary <- ens_future_df %>% 
        summarise(mean = mean(chla_sqrt_future, na.rm =T), 
                  median = median(chla_sqrt_future, na.rm =T), 
                  Q1 = quantile(chla_sqrt_future, 0.25, na.rm =T), 
                  Q3 = quantile(chla_sqrt_future, 0.75, na.rm =T), 
                  min = min(chla_sqrt_future, na.rm = T),
                  max = max(chla_sqrt_future, na.rm = T))
      
      print("Future (yr 2100)")
      print(ens_future_summary) 
      
      ens_delta_summary <- ens_baseline_df %>% select("chla_sqrt_baseline", "x", "y") %>% 
        left_join(ens_future_df %>% select("chla_sqrt_future", "x", "y"), by = c("x","y")) %>% 
        mutate("chla_delta" = (((chla_sqrt_future - chla_sqrt_baseline)/chla_sqrt_baseline))) %>% 
        summarise(mean = mean(chla_delta, na.rm =T), 
                  median = median(chla_delta, na.rm =T), 
                  Q1 = quantile(chla_delta, 0.25, na.rm =T), 
                  Q3 = quantile(chla_delta, 0.75, na.rm =T), 
                  min = min(chla_delta, na.rm = T),
                  max = max(chla_delta, na.rm = T))
        
      print("Change by 2100 relative to 2015 (reported in proportional change)")
      print(ens_delta_summary)
    }
  }
  
  #summary_stats_chlos(ensemble_median)
  
##